# Number of days a URL will be keep in the database
application:
    valid-days: ${APP_VALID_DAYS:365}

spring:
    data:
        mongodb:
            uri: ${MONGODB_URI:mongodb://127.0.0.1:27017/url_shortener_db}
