# Number of days a URL will be keep in the database
application:
    valid-days: ${APP_VALID_DAYS:365}

spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: password
